### ISSUE TITLE
receiving "Error: bad escape \d at position 7" on all videos

### ISSUE THREAD

**Issue by andlabs** [egbertbouman/youtube-comment-downloader#109]
Python 3.9 or 3.10 from MacPorts on macOS 10.12.6. For any video I try, it starts to download the comments, and then immediately gives up with "Error: bad escape \d at position 7". I don't see any way to get debugging info, so.

I am invoking as

```
python3 ~/extsrc/youtube-comment-downloader/youtube_comment_downloader/__main__.py --youtubeid ID --output FILE
```

and the third-party Python dependency modules are also installed from MacPorts.

**Comment by egbertbouman** [comment]
I'm unable to reproduce the error, but did find a similar issue [here](https://stackoverflow.com/questions/71498132/error-in-heroku-regex-regex-core-error-bad-escape-d-at-position-7-when-usin).

Perhaps it's due to `dateparser` and `regex` not being compatible. If you're running an older version (<1.1.1) of `dateparser`, you could try and see if updating it fixes the problem.

**Comment by andlabs** [comment]
All right, MacPorts did not actually update dateparser yet, but I tried installing it from pip in a venv and 1.1.1 does indeed work. Thanks!
