### ISSUE TITLE
Is possible to see the count of all comments too??

### ISSUE THREAD

**Issue by sleiter88** [egbertbouman/youtube-comment-downloader#24]
I want to know the counts of comments on the video, I mean, only the number ("148 comments.").

Is possible, I don't know how to find his CSS tag.

**Comment by Architector4** [comment]
The comment count on the video page is unreliable in my experience, so I think the only reliable way is to just count the amount of comments you get.
Since they are being output in JSON format with one line for each comment, it looks like you could just count the number of lines in your output file.

**Comment by sleiter88** [comment]
@Architector4 Actually the script show you how many comments it found but it's basically a count variable. I need to get the comment number without iterate on ajax response.

**Comment by d0tN3t** [comment]
This is the selector you probably want to add if you're looking to grab the count of comments without doing an iteration count or `len(list)` 

![image](https://user-images.githubusercontent.com/11362484/61554330-4da85c00-aa22-11e9-880c-999f462036e9.png)
