### ISSUE TITLE
Disabled comments in videos causes the script to hang

### ISSUE THREAD

**Issue by nihiluis** [egbertbouman/youtube-comment-downloader#32]

**Comment by egbertbouman** [comment]
Could you give me an example Youtube ID?

**Comment by Architector4** [comment]
I guess this is the kind of a video they are talking about:
https://www.youtube.com/watch?v=4YYvBLAF4T8

**Comment by d0tN3t** [comment]
@egbertbouman  @Architector4 

Yeah , I did a try-catch for this issue the comment_count section. I didn't bring it up because I modified the code for the whole channel's anthology, vs going one at time. 

So I targeted the comment count in the runs field.

```
def qc(i, value):
    try:
        return i[value]
    except:
        return 0

def compile_data(video_id):
    try:
        html, com_count = download_comments_new_api(video_id)
        comment_count = [int(qc(i["runs"][0], "text").lower().replace("comments","").replace(",","").replace("comment","").strip()) for i in search_dict(com_count, "countText")][0]
    except Exception as e:
```
Not the prettiest, but it got the job done.

**Comment by egbertbouman** [comment]
It should be fixed now. If it happens again, please reopen.
