### ISSUE TITLE
Extract author's channel ID

### ISSUE THREAD

**Issue by pupkinvaska** [egbertbouman/youtube-comment-downloader#39]
Why not to extract author's channel ID?

Just add
`'channel': item[0].get('href'),`
in the loop of extract_comments function

**Comment by Architector4** [comment]
I think it's because it's out of the scope for this tool. I mean, if that gets added, why not also extract title and description? Likes and dislikes? Amount of subscribers? Whatever else? At that point, it wouldn't be just a "youtube-comment-downloader" anymore, to be honest.

Though since all data is JSON anyways, I don't think it would hurt adding such functionality. Just my random 2 cents.

**Comment by pupkinvaska** [comment]
This is useful data for further formatting a commenter's name as a link rather than plain text

**Comment by egbertbouman** [comment]
@pupkinvaska Since you find it useful, I've just added the author's channel to the JSON output.
