### ISSUE TITLE
recomended program for viewing & editing comments

### ISSUE THREAD

**Issue by terrypa** [egbertbouman/youtube-comment-downloader#63]
Hi, newbe question, do you recomend some txt editor (windows) for viewing this json file (in notepad++) looks like mess

btw. ty for scritp its V. usefull

**Comment by sinepgnol** [comment]
I join the request. Something to view the comments in a well-arranged way would come in handy.

**Comment by sinepgnol** [comment]
I wrote a small little script for this: https://github.com/sinepgnol/YTB-comments-from-JSON-to-a-well-arranged-way

**Comment by minamotorin** [comment]
I wrote same script with [jq](https://github.com/stedolan/jq) for CLI:

```sh
cat "comment.json"                                      |
sed '$!s/$/,/; 1s/^/[/; $s/$/]/'                        |
jq -r '
  map( .cid |= sub("\\..*";""))                         |
  group_by(.cid)                                        |
  map(
    [
      (.[0:1]                                           |
        map(
          .author |= sub("^"; "---\n")                  |
          .text   |= gsub("\n"; "\n  ")                 |
          .text   |= sub("^"; "\n  ")
        )
      )[]
    ,
      (.[1:]                                            |
        map(
          .author |= sub("^"; "    ")                   |
          .text   |= gsub("\n"; "\n      ")             |
          .text   |= sub("^"; "\n      ")
        )
      )[]
    ]
  )
  [][]                                                  |
  .author + " (" + .votes + " : " + .time + "):" + .text
'                                                       |
sed '$G; $s/$/---/'
```

**Comment by Cyrix126** [comment]
> I wrote same script with [jq](https://github.com/stedolan/jq) for CLI:
> 
> ```shell
> cat "comment.json"                                      |
> sed '$!s/$/,/; 1s/^/[/; $s/$/]/'                        |
> jq -r '
>   map( .cid |= sub("\\..*";""))                         |
>   group_by(.cid)                                        |
>   map(
>     [
>       (.[0:1]                                           |
>         map(
>           .author |= sub("^"; "---\n")                  |
>           .text   |= gsub("\n"; "\n  ")                 |
>           .text   |= sub("^"; "\n  ")
>         )
>       )[]
>     ,
>       (.[1:]                                            |
>         map(
>           .author |= sub("^"; "    ")                   |
>           .text   |= gsub("\n"; "\n      ")             |
>           .text   |= sub("^"; "\n      ")
>         )
>       )[]
>     ]
>   )
>   [][]                                                  |
>   .author + " (" + .votes + " : " + .time + "):" + .text
> '                                                       |
> sed '$G; $s/$/---/'
> ```
> 
> I missed Windows. `cat` and `sed` (and also `jq`) will not be installed in Windows by default.

for some reasons your script would print 15 times each comments. 
Adding 
`| sed 's/^ *//g' | awk '{$1=$1}1' | awk ' !x[$0]++' | sed 's/\(.*):\)/\n\1/g'`
solved the issue.

**Comment by minamotorin** [comment]
Thank you for replying! No problem with my environment (jq-1.6, BSD sed and BSD cat). I think your original json file is 15 loops of original comments. Run ` grep "some cid" /pass/to/comment.json `. If it is true, adding ` sort -u ` in first of my script and solve the issue.

I'm interested in your addtional scripts. Could you tell me how ` | sed 's/^ *//g' | awk '{$1=$1}1' | awk ' !x[$0]++' | sed 's/\(.*):\)/\n\1/g' ` works?

**Comment by Cyrix126** [comment]
you are right, the original comment.json was containing multiple times the same comment. I wonder why. 

first sed is for deleting space at start of line, because same comments was having different  number of spaces at the beginning of the line, then awk can show dupplicates lines only one time. Then the last sed is adding a new line after the line with the name of the author.
If I used only sort -u at the end, it would messed up everything because the name of the author would not be associated with the right comment (because every lines would be sorted). But I wasn't aware that the problem originated from the json file so adding it at the beginning is better, but it could be an issue because the comments would not sorted by time.

**Comment by minamotorin** [comment]
I learnd awk techniques. Thanks!

That was bug but fixed. See #68.

The space at start of line makes distiniction of comment types. Normal comments has 2 spaces and that's replies has 6 spaces. This script does not sort by time because it will break relation between normal comments and replies.

But you are right, ` sort -u ` will break the relation. Use ` sed -n '1h; 1!G; /^\(.*\)\n\1/q; s/\n.*//; p' ` instead of ` sort -u ` and solve this issue.

**Comment by minamotorin** [comment]
I think ` sort -u ` does not break the relation because of rule of cid but using ` sed -n '1h; 1!G; /^\(.*\)\n\1/q; P' ` is good idea because ` sort -u ` is slow. Or your json file does not contain any replies because of bug.

**Comment by archmord** [comment]
You can view json file in Firefox browser

**Comment by sinepgnol** [comment]
Wow, don’t tell me! TextEdit also works.

**Comment by elibroftw** [comment]
@terrypa Use VSCode. It can also auto format json files.

**Comment by raelb** [comment]
Perhaps author can add a command line option to pretty print output.
e.g. --pretty 1

**Comment by egbertbouman** [comment]
The newest version has a `--pretty` option, which will change the output format to indented JSON.
