### ISSUE TITLE
Incorrect time, comment tree

### ISSUE THREAD

**Issue by 174n** [egbertbouman/youtube-comment-downloader#77]
1. Time is saved not as timestamp or datetime, but as relative time with language based on ip. For example `time: 'vor 6 Jahren'` (6 years ago).

2. There is no way tho know if a comment is an answer to other comment.

For example if I have such a comment tree:
```
├── comment 1
│   ├── comment 2
│   └── comment 3
└── comment 4
```

The comments are saved like this

```
{ comment1 }
{ comment2 }
{ comment3 }
{ comment4 }
```

So there is no way to know if comment2 is an answer to the comment1. And the json should be probably saved as a valid json (like an array of objects instead of objects separated by new line).

Thanks for your project anyway, nice work

**Comment by d0tN3t** [comment]
@Rundik 

Correct, the time the is returned comes back from YouTube's API and they convert it over on their end on how it should be printed out (6 months, 1 year). If you ever use their API with a key you can, in fact, get the comment's date but then you run into their rules/limits of how many comments you can download in a 24 hour period.

As for the tree in question, I think it's more of a preference, to be honest. When I first started working with this script I wasn't a fan of the new-line delimitation but now it's become my go-to use. You can still group the comments how you want by looking at the `cid` key. If a key looks like this <xxxxxxxxx.xxxxxxxxx> then it has a parent because it is the reply of that parent. You will notice in the image I've provided that everything to the left of the period is the parent ID and everything to the right of the period is the unique reply ID. I hope this makes sense. 

Of course, you have the option in the script to request the comments be incoming-sorted by popularity or date (which I believe everything comes in ascending order, but I could be mistaken). So they are in order, you would just need to group them according to your needs.

![image](https://user-images.githubusercontent.com/11362484/120739894-c4845c00-c4b7-11eb-94fd-106630ed3a57.png)
